### PR TITLE
Change title parser to use regex

### LINKED ISSUE #20: list index out of range
Traceback (most recent call last):
  File "galaxy_library_export.py", line 52, in <module>
    row['title'] = result[1].split('"')[3]
IndexError: list index out of range

### PR DESCRIPTION
**Pull request by AB1908**
This probably fixes #20. Should I add regex parsers for the rest of the fields as well?

### CODE REVIEW

**Comment by toastmonster** [comment]
It didn't give any error, but the gameDB.csv file has no titles in it now.
[gameDB.zip](https://github.com/AB1908/GOG-Galaxy-Export-Script/files/4567544/gameDB.zip)

**Comment by AB1908** [comment]
Hmm. Wait.

**Comment by toastmonster** [comment]
What if I sent you a copy of my `galaxy-2.0.db`?  Is that safe to do?

**Comment by AB1908** [comment]
Well...I'd generally advise against doing that. It honestly boils down to how well I can handle edge cases like the odd quotation mark or unicode. I'm only a beginner at this so a lot of those are slipping past me.

**Comment by AB1908** [comment]
I'm incredibly sorry. Fixing.

**Comment by AB1908** [comment]
How shameful. I added an extra space for no reason. Tested and confirmed to work.

**Pull request merged**
