### PR TITLE
Use official platform list

### PR DESCRIPTION
**Pull request by JanPokorny**
Hello! Looks like you had some problems naming platforms. There is an official platform list here: https://github.com/gogcom/galaxy-integrations-python-api/blob/master/PLATFORM_IDs.md -- I have used it in the code and replaced the now useless list in the README with link to it.

### CODE REVIEW

**Comment by AB1908** [comment]
I think there's way more platforms than those listed officially. I'll keep this one open for now and do some more investigation. For the record, I've obtained my list from looking at the database itself. That being said, thanks for the pull request!

**Comment by JanPokorny** [comment]
@AB1908 What makes you think there are more? Did you encounter any not listed there? If you did, it might be best to report it, as that list is an official dev documentation from GOG.

**Comment by AB1908** [comment]
For example, Nuuvem is missing from your list and from GOG's while it is in the database, specifically in the `platformList` table list I think. What do you think should be done?

**Comment by JanPokorny** [comment]
That's interesting, there are some pretty obvious platforms missing from the list, including Rockstar and Twitch which even have integrations. I have re-added your extra platforms, which, for reference, were:

- fxstore
- generic
- gamesessions
- gog
- indiegala
- minecraft
- nuuvem
- oculus
- playfire
- rockstar
- twitch

I have opened an issue with the API repository: https://github.com/gogcom/galaxy-integrations-python-api/issues/140

**Comment by AB1908** [comment]
Cool! I'll go ahead and merge this. Thanks for the corrections!

**Comment by JanPokorny** [comment]
Wait a sec, found a mistake

**Comment by AB1908** [comment]
Comment the mistake here and I'll include it in a future patch. I'd rather not mess with the history because I'm not that experienced at rewriting it to my liking.

**Comment by JanPokorny** [comment]
@AB1908 #13

**Pull request merged**
