### PR TITLE
List and number games from CSV file to text file.

### PR DESCRIPTION
**Pull request by mabackma**
If you want a list of your games you can print them out with print_gameDB.py
It prints two lists of your games, one in alphabetical order and the other list is supposed to be sorted in chronological order, but I think it's being sorted by the latest update to the game though.

### CODE REVIEW

**Comment by AB1908** [comment]
Is this not doable via the default tool? Just trying to understand where this comes in handy and what it covers as opposed to the original script.

**Comment by mabackma** [comment]
My script prints out only the name of the games so it's much more readable than the CSV. The CSV file contains too much information if you only want to keep track of the games that you already own. It comes in handy if you own a lot of games. Try it out :)

**Comment by mabackma** [comment]
I own over 800 games so I've been using it a lot to see that I won't accidentally buy the same games over again.

**Comment by AB1908** [comment]
I see. I'd strongly urge that you either create a separate folder called helper scripts so people don't end up confusing one for the other or maintain this separately. It's a silly thing to worry about but I'm trying to keep less technical users in mind.

**Comment by mabackma** [comment]
Ok I will do that

**Comment by AB1908** [comment]
Could you also gitignore the idea stuff from your ide?

**Comment by mabackma** [comment]
Sure

**Comment by mabackma** [comment]
A cleaner version of the script: Now it only prints a numbered list of all the games into my_games.txt file and the script is in the helper_scripts folder. I also removed the .idea folder and the gitignore file was changed to also ignore the my_games.txt file created.

**Comment by AB1908** [comment]
Thanks for everything!

**Comment by mabackma** [comment]
Thank you! That was my first GitHub contribution.

**Pull request merged**
